### ISSUE TITLE
Two sdk version installed

### ISSUE THREAD

**Issue by Enngage** [Kentico/cloud-expressjs-app#10]
There are 2 js sdk versions installed - https://github.com/Kentico/cloud-expressjs-app/blob/master/package.json#L20

Remove the old one.

**Comment by kentico-ericd** [comment]
solved in [c51ba69187bcc937b4b023a8ea697f23bd7727b6](https://github.com/Kentico/cloud-expressjs-app/commit/c51ba69187bcc937b4b023a8ea697f23bd7727b6)
