### ISSUE TITLE
Solve eslint issues

### ISSUE THREAD

**Issue by Enngage** [Kentico/cloud-expressjs-app#9]
Eslint is used to 'enforce' good coding practices so if you have to disable it for certain lines, you have to have a good reason. Currently, there is a lot of comments like this https://github.com/Kentico/cloud-expressjs-app/blob/master/repositories/coffee-repository.js#L77 that disable eslint. Rather than using this, try to actually fix the code.

**Comment by kentico-ericd** [comment]
solved in [e0e3210558fa2d3441d6f2363ea261693078568f](https://github.com/Kentico/cloud-expressjs-app/commit/e0e3210558fa2d3441d6f2363ea261693078568f)
